fail_fast: false

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        types: [python]
        language: system

      - id: isort
        name: isort
        entry: isort
        types: [python]
        language: system
        args: ["--profile", "black", "--filter-files",]

      - id: mypy
        name: mypy
        entry: mypy
        types: [python]
        language: system
        args: ["--pretty"]

      - id: pylint
        name: pylint
        entry: pylint
        types: [python]
        language: system
        args: ["-rn", "-sn",]
