[tool.poetry]
name = "agequip-rw"
version = "0.0.1"
description = "Data collection of equipments for Artery Gear: Fusion"
authors = ["PythonTryHard <31789326+PythonTryHard@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "agequip_rw"}]

[tool.poetry.dependencies]
python = "^3.10, <3.12"
opencv-python = "^4.6.0.66"
paddleocr = "^2.6.0"
mitmproxy = "^8.1.1"
python-dotenv = "^0.21.0"
pure-python-adb = "^0.3.0.dev0"
loguru = "^0.6.0"
colormath = {git = "https://github.com/PythonTryHard/python-colormath.git"}
paddlepaddle = "^2.3.2"
pyzmq = "^24.0.1"
scikit-image = "^0.19.3"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.15.3"
black = "^22.8.0"

[tool.black]
line-length=120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
